import {test,expect} from './fixtures.mjs';
import {isolatedServer,isolatedPeripheral,players,revision,seek,tile} from './game-helpers.mjs';

for(const peripheral of [false,true]) test(`progressive replay: ${peripheral?'peripheral':'controller'} seek, refresh and final handoff`,async({review},testInfo)=>{
  test.setTimeout(120000);
  const edit=c=>{c.match_defaults.max_tick=6000;c.match_defaults.stall_ticks=6000;};
  const env={ATEMPORAL_PREVIEW_TEST_DELAY_MS:'150'};
  const server=peripheral?await isolatedPeripheral(testInfo,edit,env):await isolatedServer(testInfo,edit,()=>{},[],env);
  review.afterClose(server.stop);
  const [a,b]=await players(review,server.url);
  await a.getByRole('button',{name:'Start match',exact:true}).click();
  await revision(a,0);await revision(b,0);
  const start=await a.evaluate(()=>{const e=window.atemporal.entities().find(e=>e.owner===0&&e.type_key==='constructor');return{x:e.x,y:e.y};});
  await tile(a,start);await a.keyboard.press('f');await tile(a,{x:start.x+2,y:start.y});
  await a.locator('#commit').click();await b.locator('#commit').click();
  await expect.poll(()=>a.evaluate(()=>window.atemporal.preview?.through_tick??0)).toBeGreaterThanOrEqual(100);
  expect(await a.evaluate(()=>window.atemporal.latest)).toBe(0);
  await a.keyboard.press('End');const edge=await a.evaluate(()=>window.atemporal.playhead);
  await a.locator('#play').click();
  await expect.poll(()=>a.evaluate(()=>window.atemporal.playhead)).toBeGreaterThan(edge);
  await a.locator('#play').click();
  const before=await a.evaluate(()=>window.atemporal.preview.through_tick);
  await a.fill('#tick-input','73');
  await expect.poll(()=>a.evaluate(()=>window.atemporal.preview?.through_tick??0)).toBeGreaterThan(before);
  await expect(a.locator('#tick-input')).toHaveValue('73');
  await a.locator('#tick-input').press('Enter');
  await expect.poll(()=>a.evaluate(()=>window.atemporal.exact?.tick)).toBe(73);
  await a.keyboard.press('Escape');
  const snapshot=await a.evaluate(()=>window.atemporal.exact.state);
  expect(snapshot.entities.find(e=>e.owner===0&&e.type_key==='constructor').tile).toEqual({x:start.x+2,y:start.y});
  await expect(a.locator('#commit')).toBeDisabled();
  await expect(a.locator('#outcome-banner')).toContainText('Result pending');
  await expect(a.locator('#timeline')).toHaveAttribute('data-available-through',/\d+/);
  await expect(a.locator('#scoreboard [data-player="0"]')).toHaveAttribute('data-wins','0');
  await expect(a.locator('#scoreboard')).toContainText('result pending');
  await review.capture('viewing-completed-prefix',a);
  await a.locator('#play').click();
  await expect.poll(()=>a.evaluate(()=>window.atemporal.playhead)).toBeGreaterThan(73);
  await a.locator('#play').click();
  await a.reload();
  await expect.poll(()=>a.evaluate(()=>window.atemporal?.viewingPreview && window.atemporal?.current)).toBe(1);
  await seek(a,73);
  expect(await a.evaluate(()=>window.atemporal.exact.state)).toEqual(snapshot);
  expect(await a.evaluate(()=>{const g=window.atemporal;const e=g.entities().find(e=>e.owner===0&&e.type_key==='constructor');const [x,y]=g.renderer.screen(e.x+.5,e.y+.5);return x>0&&x<innerWidth&&y>110&&y<document.getElementById('panels').getBoundingClientRect().top;})).toBe(true);
  await review.capture('preview-after-refresh',a);
  await revision(a,1);await revision(b,1);
  expect(await a.evaluate(()=>window.atemporal.playhead)).toBe(73);
  await seek(a,73);
  expect(await a.evaluate(()=>window.atemporal.exact.state)).toEqual(snapshot);
  await expect(a.locator('#commit')).toBeEnabled();
  await expect(a.locator('#outcome-banner')).not.toContainText('Result pending');
  await review.capture('verified-replay-handoff',a);
});
